#!/usr/bin/python

import os,sys,time,commands

os.system('dialog --infobox "WELCOME IN LINUX" 10 30')
time.sleep(1)

os.system('dialog --msgbox "CLICK OK" 10 30')

os.system('dialog --menu "chose any one option" 20 30 2 1 "registered" 2 "not registered"  2>/tmp/ch.txt')
f=open('/tmp/ch.txt')
ch=f.read()
f.close()
print ch
if ch == '1' :
	execfile('regis_pre.py') #pre registered user
	
elif ch == '2' :
	execfile('register.py')	#for new user

else :
	exit()	

